### PR TITLE
Fixes dead link to Karabiner Configuration Reference Manual

### PR DESCRIPTION
**Pull request by kushie0**

### CODE REVIEW

**Review by zhukant — APPROVED** [review]

**Comment by zhukant** [comment]
@kushie0 thanks so much!! I’m flattered that you found my repo, do you enjoy the set-up? I can’t live without it! 😁

**Comment by kushie0** [comment]
yes i have wanted this kind of functionality for a long time, im excited to have found it :)

**Comment by zhukant** [comment]
@kushie0 awesome! :) You may need to tweak one or more of the activation keys or mappings if you use QWERTY (I use Dvorak and didn’t really QA for QWERTY), but it should be fairly straightforward!

**Comment by zhukant** [comment]
@kushie0 ooh, looks like my read me is out of date. I think I completed the Z-arrow mode and dropped the toggle that switches it on with the 8 key entirely. I definitely use the Z arrow mode all the time now and it works well. I’ll update the readme later!

**Pull request merged**
